stages:
  - build
  - deploy

build-and-deploy:
  image: andreysenov/firebase-tools:latest
  stage: build
  script:
    - yarn install --frozen-lockfile
    - yarn build
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  only:
    - main
    - f/login
